// Support status of every Codex app-server request Pi Remote answers. Requests not
// listed here return -32601. METHODS.md is generated from this table and the vendored
// schema by `node scripts/methods-doc.mjs`.
//   implemented: mapped to Pi, possibly a subset that rejects unsupported parameters
//   empty:       Pi has no such resource; returns an empty result
export const methodStatus = {
  'initialize': ['implemented'],
  'account/read': ['implemented', 'Returns no account information; Pi manages model authentication'],
  'modelProvider/capabilities/read': ['implemented', 'Codex provider capability flags are false; this does not restrict Pi tools'],
  'config/read': ['implemented', 'Current Pi model and thinking level; no Codex config layers'],
  'configRequirements/read': ['implemented', 'Only Pi execution without a Codex sandbox'],
  'permissionProfile/list': ['implemented', 'Only :danger-full-access; Pi permission hooks still apply'],
  'model/list': ['implemented', 'All Pi models with their supported thinking levels'],
  'skills/list': ['implemented', 'Pi skills, read-only'],
  'thread/start': ['implemented'],
  'thread/list': ['implemented'],
  'thread/read': ['implemented'],
  'thread/resume': ['implemented', 'Sessions open in another Pi are read-only'],
  'thread/fork': ['implemented', 'Whole thread, through a turn, or before a turn'],
  'thread/settings/update': ['implemented', 'Model and thinking level only'],
  'thread/loaded/list': ['implemented'],
  'thread/turns/list': ['implemented'],
  'thread/items/list': ['implemented'],
  'thread/name/set': ['implemented'],
  'thread/compact/start': ['implemented'],
  'thread/revert': ['implemented', 'Keeps the abandoned branch in the Pi session file'],
  'thread/archive': ['implemented', 'Moves the session file to the macOS Trash'],
  'thread/unarchive': ['implemented', 'Restores the session file from the Trash'],
  'thread/unsubscribe': ['implemented'],
  'thread/delete': ['implemented', 'Moves the session file to the macOS Trash and removes the thread from Remote'],
  'thread/search': ['implemented', 'Session names and message text on the active branch'],
  'thread/searchOccurrences': ['implemented', 'Visible user messages and final assistant messages, with UTF-16 match ranges and turn cursors'],
  'thread/timeline/list': ['implemented', 'Ordinary history only; newest page first, chronological order within each page'],
  'thread/shellCommand': ['implemented', 'Pi `!` command: runs Pi user_bash hooks without a sandbox and adds the output to the session context'],
  'turn/start': ['implemented'],
  'turn/steer': ['implemented'],
  'turn/interrupt': ['implemented'],
  'fs/readFile': ['implemented', 'Private attachment cache, not the host filesystem'],
  'fs/writeFile': ['implemented', 'Private attachment cache, not the host filesystem'],
  'fs/createDirectory': ['implemented', 'Private attachment cache, not the host filesystem'],
  'fs/getMetadata': ['implemented', 'Private attachment cache, not the host filesystem'],
  'fs/readDirectory': ['implemented', 'Private attachment cache, not the host filesystem'],
  'fs/remove': ['implemented', 'Private attachment cache, not the host filesystem'],
  'fs/copy': ['implemented', 'Private attachment cache, not the host filesystem'],
  'thread/queue/list': ['implemented', 'Durable pending submissions; text and base64 data URL images only'],
  'thread/queue/add': ['implemented', 'Loaded Remote-owned threads automatically consume queued input; interrupt pauses consumption'],
  'thread/queue/update': ['implemented'],
  'thread/queue/delete': ['implemented'],
  'thread/queue/reorder': ['implemented'],
  'thread/queue/start': ['implemented', 'Loaded Remote-owned threads only; resumes a paused queue. Uncertain dispatches are not retried: inspect history before deleting and resubmitting the entry'],
  'thread/goal/get': ['empty'],
  'collaborationMode/list': ['empty'],
  'plugin/installed': ['empty'],
  'threadSection/list': ['empty'],
  'thread/backgroundTerminals/list': ['empty', 'Pi has no background terminal registry'],
  'hooks/list': ['empty'],
  'plugin/list': ['empty'],
  'app/list': ['empty'],
  'mcpServerStatus/list': ['empty'],
  'experimentalFeature/list': ['empty'],
  'command/exec': ['implemented', 'Official Codex Seatbelt sandbox via `codex sandbox`; readOnly or workspaceWrite only, no network, no PTY'],
  'command/exec/write': ['implemented'],
  'command/exec/terminate': ['implemented'],
};
